### ISSUE TITLE
Ability to set headers in response

### ISSUE THREAD

**Issue by brendanvinson** [jeffijoe/koa-respond#2]
Would be great if there was the ability to set response headers as a part of of the call, eg. `ctx.ok("It's OK", {'x-status': 'totally cool'});`.

We can, of course use `ctx.set` (I'm assuming) before we call `ctx.<method>`, but using just the one call would be better.

**Comment by jeffijoe** [comment]
Not a bad idea - feel free to submit a PR :)

**Comment by brendanvinson** [comment]
Having one issue with the tests that seems odd:

```js
1) respond sets all options on the context:
     TypeError: ctx.set is not a function
      at respond (lib/respond.js:29:11)
      at Context.<anonymous> (test/lib/respond.spec.js:27:5)
```

Since the docs for Koa [say that is is too a function](https://github.com/koajs/koa/blob/master/docs/api/response.md#responsesetfields) I'm a bit at a loss.

My code:

```js
return function respond (ctx, status, payload, headers) {
    ctx.status = status

    if (headers !== undefined && Object.keys(headers).length > 0) {
      ctx.set(headers)
    }
...
```

Test code:
```js
it('sets all options on the context', function () {
    respond(ctx, 200, 'hello world', {'x-status': 'ok'})
    ctx.status.should.equal(200)
    ctx.body.should.equal('hello world')
    ctx.get('x-status').should.equal('ok')
  })
```

**Comment by jeffijoe** [comment]
Thats because the tests use a simple mock, its not actually a koa context.

Sent from my iPhone

On 1 Mar 2017, at 19.13, Brendan Vinson <notifications@github.com<mailto:notifications@github.com>> wrote:


Having one issue with the tests that seems odd:

1) respond sets all options on the context:
     TypeError: ctx.set is not a function
      at respond (lib/respond.js:29:11)
      at Context.<anonymous> (test/lib/respond.spec.js:27:5)

Since the docs for Koa say that is is too a function<https://github.com/koajs/koa/blob/master/docs/api/response.md#responsesetfields> I'm a bit at a loss.

My code:

return function respond (ctx, status, payload, headers) {
    ctx.status = status

    if (headers !== undefined && Object.keys(headers).length > 0) {
      ctx.set(headers)
    }
...

Test code:

it('sets all options on the context', function () {
    respond(ctx, 200, 'hello world', {'x-status': 'ok'})
    ctx.status.should.equal(200)
    ctx.body.should.equal('hello world')
    ctx.get('x-status').should.equal('ok')
  })

**Comment by jeffijoe** [comment]
https://github.com/jeffijoe/koa-respond/blob/master/test/lib/respond.spec.js#L14

**Comment by brendanvinson** [comment]
Ah thanks.

I know it's is breaking change, but at this point I think makes sense for flexibility with multiple parameters reasons to make payload and headers part of an options object. So:

```js
ctx.ok({ message: 'hey there', headers: {
    'x-status' : 'ok'
} });
```

That way you could remove one or the other or have them in a different order without breaking the code. Thoughts?

**Comment by jeffijoe** [comment]
I actually prefer you first approach - setting headers is not something you usually do for every request, so `ctx.ok(payload, { 'X-Header': 'yes!' })` makes good sense to me, also seems more fluid

**Comment by brendanvinson** [comment]
If, however you want to set the headers without a payload it gets awkward:
`ctx.ok("", { 'X-Header': 'yes!' })`

**Comment by jeffijoe** [comment]
But really, since all methods return the context, you can do this with no modifications to `koa-respond` at all:

```
const handler = (ctx) => ctx.ok().set({ 'X-Header': 'yes!' })
```

**Comment by brendanvinson** [comment]
True, hadn't thought of that. In that case though, does this functionality need to be a part of the library?

**Comment by jeffijoe** [comment]
Another reason I don't want to introduce the options object as the first parameter, is that we would loose the ability to just pipe things using promises.

```
router.post('/todos', (ctx) => todoService.create(ctx.request.body).then(ctx.ok))
```

**Comment by jeffijoe** [comment]
No, I totally forgot to mention the chainability when you first proposed the change - sorry about that.

**Comment by brendanvinson** [comment]
Ok, we can close it then. 👍

**Comment by brendanvinson** [comment]
Might add documentation on that though :)

**Comment by jeffijoe** [comment]
I believe most of Koa's functions return the context itself so `respond` just follows suit. But yeah, good point!

**Comment by jeffijoe** [comment]
Alright, updated the docs. 👍
